# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# make sure the doc strings are correct, i have done some check the others

"""
Css Env Environment Implementation.
"""

from typing import Dict
from uuid import uuid4

from openenv.core.env_server.interfaces import Environment
from openenv.core.env_server.types import State

try:
    from ..models import CssAction, CssObservation
    from ..reward import compute_reward
    from .action_engine import apply_action
    from .flaw_injector import inject_flaws
except ImportError:
    from models import CssAction, CssObservation
    from reward import compute_reward
    from action_engine import apply_action
    from flaw_injector import inject_flaws


class CssEnvironment(Environment):
    """
    CSS Refinement RL Environment

    This environment simulates a CSS refinement task where
    an agent iteratively modifies CSS code to improve design quality.

    Example:
    >>> env = CssEnvironment()
    >>> obs = env.reset(task, seed=42)
    >>> print(obs.html) # <div class="card">Hello</div>
    >>> print(obs.css) # .card { color: #1a73e7; }
    >>> result = env.step(CssAction(
    ...     action_type="replace_color",
    ...     target="#1a73e7",
    ...     value="#1a6fe0"
    ... ))
    >>> print(result["observation"].css) # .card { color: #1a6fe0; }
    >>> print(result["reward"]) # 0.6
    >>> print(result["done"]) # False
    """

    # Enable concurrent WebSocket sessions.
    # Set to True if your environment isolates state between instances.
    # When True, multiple WebSocket clients can connect simultaneously, each
    # getting their own environment instance (when using factory mode in app.py).
    SUPPORTS_CONCURRENT_SESSIONS: bool = True

    def __init__(self):
        """Initialize the css_env environment."""
        self.html = "" # html string in the task
        self.css = "" # css string in the task
        self.design_tokens = {} # design tokens given in the task as a dict of token_name -> value
        self.config = {} # config given in the task to inject flaws
        self.manifest = [] # list of dicts describing flaws
        self.step_count = 0 # current step count
        self.max_steps = 20 # maximum steps
        self.state_data = {} # tracks progress

    def reset(self, task: Dict, seed: int) -> CssObservation:
            """
            task = {
                "html": str,
                "css": str,
                "design_tokens": dict,
                "config": dict,
                "difficulty": "easy" | "medium" | "hard"
            }
            """

            self.step_count = 0

            self.html = task["html"]
            self.design_tokens = task["design_tokens"]
            self.config = task["config"]
            self.difficulty = task.get("difficulty", "easy")

            clean_css = task["css"]

            result = inject_flaws(clean_css, self.design_tokens, self.config, seed)

            self.css = result["css"]
            self.manifest = result["manifest"]

            self.state_data = {
                "step_count": 0,
                "initial_manifest": self.manifest,
            }

            return CssObservation(
                html=self.html,
                css=self.css,
                design_tokens=self.design_tokens,
                violations=result["hints"] if self.difficulty == "easy" else None
            )

    def step(self, action: CssAction) -> Dict:
        """
        Execute a step in the environment by applying the action generated by the agent to the CSS.
        """

        self.css, is_changed = apply_action(self.css, action)

        scores = self._run_graders() # placeholder until graders are plugged in. arijit

        # Compute reward
        reward = compute_reward(
            scores,
            action_valid=is_changed,
            done=self._is_done(scores)
        )

        self.step_count += 1
        # arijit i dont know what is happening here with the is_done thing
        done = self._is_done(scores) or self.step_count >= self.max_steps

        obs = CssObservation(
            html=self.html,
            css=self.css,
            design_tokens=self.design_tokens,
            violations=None  # only shown at reset
        )

        info = {
            "scores": scores,
            "step_count": self.step_count,
            "changed": is_changed
        }

        return {
            "observation": obs,
            "reward": reward,
            "done": done,
            "info": info
        }

    @property
    def state(self) -> State:
        """
        Get the current environment state.

        Returns:
            Current State with episode_id and step_count
        """
        return self.state_data
    

    # you will have to change these later as per your thing
    def _run_graders(self) -> Dict[str, float]:
        """
        Temporary dummy graders (Person 2 will replace this).
        """

        return {
            "color": 0.5,
            "spacing": 0.5,
            "typography": 0.5,
            "contrast": 0.5,
            "cleanliness": 0.5,
            "design_quality": 0.5,
        }

    def _is_done(self, scores: Dict[str, float]) -> bool:
        return all(v >= 0.95 for v in scores.values())
